### ISSUE TITLE
No metrics

### ISSUE THREAD

**Issue by MiStErLu** [baltuonis/prometheus-bigbluebutton-exporter#1]
Hello,

    We try to launch your docker v2 on our BigBlueButton instance.

    We can see many "go" metrics buy nothing about number of meeting, largest meetings, number of user connected...
    Any idea what we do wrong ?

Bests regards,
MiStErLu
Université of Strasbourg.

**Comment by baltuonis** [comment]
Make sure you set API, secret right
```
docker container run --rm -p 9688:9688 bigbluebutton-exporter --bbb.api=https://yoursite.com/bigbluebutton/api/ --bbb.secret=secret
```

You can add `--debug` flag for more info
